const categories = [
    {
        id: '1',
        navn: 'Største land etter areal',
        fasit: [
            'Russland',
            'Canada',
            'USA',
            'Kina',
            'Brasil',
            'Australia',
            'India',
            'Argentina',
            'Kasakhstan',
            'Algerie',
        ],
        kilde: 'https://www.statista.com/statistics/262955/largest-countries-in-the-world/',
        år: '2023',
    },
    {
        id: '2',
        navn: 'Største land etter befolkning',
        fasit: [
            'Kina',
            'India',
            'USA',
            'Indonesia',
            'Pakistan',
            'Brasil',
            'Nigeria',
            'Bangladesh',
            'Russland',
            'Mexico',
        ],
        kilde: 'https://www.worldometers.info/world-population/population-by-country/',
        år: '2023',
    },
    {
        id: '3',
        navn: 'Største kommuner etter befolkning',
        fasit: [
            'Oslo',
            'Bergen',
            'Trondheim',
            'Stavanger',
            'Bærum',
            'Kristiansand',
            'Drammen',
            'Asker',
            'Lillestrøm',
            'Fredrikstad',
        ],
        kilde: 'https://www.ssb.no/befolkning/folketall/artikler/norges-100-mest-folkerike-kommuner/tabell-1.norges-100-mest-folkerike-kommuner',
        år: '2021',
    },
    {
        id: '4',
        navn: 'Mest fulgte personer på Instagram',
        fasit: [
            'Instagram',
            'Cristiano Ronaldo',
            'Lionel Messi',
            'Selena Gomez',
            'Kylie Jenner',
            'Dwayne Johnson',
            'Ariana Grande',
            'Kim Kardashian',
            'Beyoncé',
            'Khloé Kardashian',
        ],
        kilde: 'https://en.wikipedia.org/wiki/List_of_most-followed_Instagram_accounts',
        år: '2023',
    },
    {
        id: '5',
        navn: 'Mest streamede sanger på Spotify',
        fasit: [
            'Blinding Lights',
            'Shape of You',
            'Dance Monkey',
            'Someone You Loved',
            'Sunflower',
            'Rockstar',
            'One Dance',
            'Stay',
            'Closer',
            'Believer',
        ],
        kilde: 'https://en.wikipedia.org/wiki/List_of_most-streamed_songs_on_Spotify',
        år: '2023',
    },
    {
        id: '6',
        navn: 'Høyest ratede filmer på IMDb',
        fasit: [
            'The Shawshank Redemption',
            'The Godfather',
            'The Dark Knight',
            'The Godfather: Part II',
            '12 Angry Men',
            'Schindler\'s List',
            'The Lord of the Rings: The Return of the King',
            'Pulp Fiction',
            'The Lord of the Rings: The Fellowship of the Ring',
            'The Good, the Bad and the Ugly',
        ],
        kilde: 'https://www.imdb.com/chart/top/',
        år: '2023',
    },
    {
        id: '7',
        navn: 'Høyest ratede TV-serier på IMDb',
        fasit: [
            'Planet Earth II',
            'Breaking Bad',
            'Planet Earth',
            'Band of Brothers',
            'Chernobyl',
            'The Wire',
            'Avatar: The Last Airbender',
            'Blue Planet II',
            'The Sopranos',
            'Cosmos: A Spacetime Odyssey',
        ],
        kilde: 'https://www.imdb.com/chart/toptv/',
        år: '2023',
    },
    {
        id: '8',
        navn: 'Rikeste land etter BNP per innbygger',
        fasit: [
            'Luxembourg',
            'Irland',
            'Sveits',
            'Qatar',
            'Norge',
            'Singapore',
            'USA',
            'Island',
            'Australia',
            'Danmark',
        ],
        kilde: 'https://www.visualcapitalist.com/worlds-richest-countries-2023-gdp-per-capita/',
        år: '2023',
    },
    {
        id: '9',
        navn: 'Rikeste personer i verden',
        fasit: [
            'Bernard Arnault',
            'Elon Musk',
            'Jeff Bezos',
            'Larry Ellison',
            'Warren Buffett',
            'Bill Gates',
            'Michael Bloomberg',
            'Carlos Slim Helu',
            'Mukesh Ambani',
            'Steve Ballmer',
        ],
        kilde: 'https://www.forbes.com/billionaires/',
        år: '2023',
    },
    {
        id: '10',
        navn: 'Største fast food-kjeder etter antall lokasjoner',
        fasit: [
            'McDonald\'s',
            'Subway',
            'Starbucks',
            'KFC',
            'Burger King',
            'Pizza Hut',
            'Domino\'s Pizza',
            'Dunkin\' Donuts',
            'Krispy Kreme',
            'Hunt Brothers Pizza',
        ],
        kilde: 'https://en.wikipedia.org/wiki/List_of_the_largest_fast_food_restaurant_chains',
        år: '2022',
    },
    {
        id: '11',
        navn: 'Land etter antall medaljer i vinter-OL',
        fasit: [
            'Norge',
            'USA',
            'Tyskland',
            'Østerrike',
            'Canada',
            'Sovjetunionen',
            'Finland',
            'Sverige',
            'Sveits',
            'Nederland',
        ],
        kilde: 'https://www.vg.no/spesial/2018/ol/tom/medaljer/index.php',
        år: '2018',
    },
    {
        id: '12',
        navn: 'Land etter antall medaljer i sommer-OL',
        fasit: [
            'USA',
            'Sovjetunionen',
            'Storbritannia',
            'Frankrike',
            'Tyskland',
            'Kina',
            'Italia',
            'Australia',
            'Ungarn',
            'Sverige',
        ],
        kilde: 'https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table',
        år: '2023',
    },
    {
        id: '13',
        navn: 'Verdens mest verdifulle selskaper',
        fasit: [
            'Apple',
            'Microsoft',
            'Saudi Aramco',
            'Alphabet',
            'Amazon',
            'Nvidia',
            'Tesla',
            'Berkshire Hathaway',
            'Meta Platforms',
            'TSMC',
        ],
        kilde: 'https://companiesmarketcap.com/',
        år: '2023',
    },
    {
        id: '14',
        navn: 'Største byer i Australia etter befolkning',
        fasit: [
            'Sydney',
            'Melbourne',
            'Brisbane',
            'Perth',
            'Adelaide',
            'Gold Coast',
            'Newcastle',
            'Canberra',
            'Sunshine Coast',
            'Central Coast',
        ],
        kilde: 'https://metropole.com.au/australias-50-largest-cities/',
        år: '2023',
    },
    {
        id: '15',
        navn: 'Største sporter i verden etter antall utøvere',
        fasit: [
            'Fotball',
            'Cricket',
            'Hockey',
            'Tennis',
            'Volleyball',
            'Bordtennis',
            'Basketball',
            'Baseball',
            'Rugby',
            'Golf',
        ],
        kilde: 'https://www.worldatlas.com/articles/what-are-the-most-popular-sports-in-the-world.html',
        år: '2022',
    },
    {
        id: '16',
        navn: 'Største religioner i verden etter antall tilhengere',
        fasit: [
            'Kristendom',
            'Islam',
            'Ubestemt',
            'Hinduisme',
            'Buddhisme',
            'Kinesisk folketro',
            'Etnisk religion',
            'Afrikansk tradisjonell religion',
            'Sikhisme',
            'Spiritisme',
        ],
        kilde: 'https://en.wikipedia.org/wiki/List_of_religious_populations',
        år: '2023',
    },
    {
        id: '17',
        navn: 'Største byer i verden etter befolkning',
        fasit: [
            'Tokyo',
            'Delhi',
            'Shanghai',
            'Sao Paulo',
            'Mexico City',
            'Cairo',
            'Mumbai',
            'Beijing',
            'Dhaka',
            'Osaka',
        ],
        kilde: 'https://en.wikipedia.org/wiki/List_of_largest_cities',
        år: '2023',
    },
    {
        id: '18',
        navn: 'Minste land i verden etter areal',
        fasit: [
            'Vatikanstaten',
            'Monaco',
            'Nauru',
            'Tuvalu',
            'San Marino',
            'Liechtenstein',
            'Marshalløyene',
            'Saint Kitts og Nevis',
            'Maldivene',
            'Malta',
        ],
        kilde: 'https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_area',
        år: '2023',
    },
    {
        id: '19',
        navn: 'Største selskaper i Norge etter omsetning',
        fasit: [
            'Equinor',
            'Norsk Hydro',
            'Yara International',
            'Telenor',
            'KLP',
            'Norgesgruppen',
            'Storebrand',
            'DNB',
            'Reitangruppen',
            'Coop Norge',
        ],
        kilde: 'https://www.kapital.no/reportasjer/2020/07/16/7547889/regnearket-med-de-500-storste-selskapene-i-norge?zephr_sso_ott=vLS8D4',
        år: '2021',
    },
    {
        id: '20',
        navn: 'Mest snakkede språk i verden',
        fasit: [
            'Engelsk',
            'Mandarin',
            'Hindi',
            'Spansk',
            'Fransk',
            'Arabisk',
            'Bengali',
            'Russisk',
            'Portugisisk',
            'Urdu',
        ],
        kilde: 'https://www.berlitz.com/blog/most-spoken-languages-world',
        år: '2023',
    },
]

export default categories;