const categories = {
    vm2026: [
        {
            id: '1',
            navn: 'Flest mål for Norges herrelandslag gjennom tidene (per juni 2026)',
            fasit: [
                'Erling Haaland (55)',
                'Jørgen Juve (33)',
                'Einar Gundersen (26)',
                'Alexander Sørloth (26)',
                'Harald Hennum (25)',
                'John Carew (24)',
                'Ole Gunnar Solskjær (23)',
                'Tore André Flo (23)',
                'Gunnar Thoresen (22)',
                'Steffen Iversen (21)',
            ],
            kilde: 'https://www.fotball.no/landslag/norge-a-herrer/?underside=statistikk',
            år: '2026',
        },
        {
            id: '2',
            navn: 'De ti siste VM-vinnerne (herrer, 1986–2022)',
            fasit: [
                'Argentina (2022)',
                'Frankrike (2018)',
                'Tyskland (2014)',
                'Spania (2010)',
                'Italia (2006)',
                'Brasil (2002)',
                'Frankrike (1998)',
                'Brasil (1994)',
                'Tyskland (1990)',
                'Argentina (1986)',
            ],
            kilde: 'https://www.foxsports.com/soccer/fifa-world-cup/history',
            år: '2022',
        },
        {
            id: '3',
            navn: 'Land med flest mål i VM gjennom tidene (herrer, t.o.m. 2022)',
            fasit: [
                'Brasil (237)',
                'Tyskland (232)',
                'Argentina (152)',
                'Frankrike (136)',
                'Italia (128)',
                'Spania (108)',
                'England (104)',
                'Nederland (96)',
                'Uruguay (89)',
                'Ungarn (87)',
            ],
            kilde: 'https://footballwhispers.com/blog/the-10-top-scoring-nations-in-fifa-world-cup-history/',
            år: '2022',
        },
        {
            id: '4',
            navn: 'Land med flest vunne kamper i VM gjennom tidene (herrer, t.o.m. 2022)',
            fasit: [
                'Brasil (76)',
                'Tyskland (67)',
                'Argentina (47)',
                'Italia (45)',
                'Frankrike (39)',
                'England (32)',
                'Spania (31)',
                'Nederland (30)',
                'Uruguay (25)',
                'Belgia (21)',
            ],
            kilde: 'https://www.fifa.com/en/tournaments/mens/worldcup/articles/teams-most-victories-wins',
            år: '2022',
        },
        {
            id: '5',
            navn: 'Flest landskamper for Norges herrelandslag gjennom tidene',
            fasit: [
                'John Arne Riise (110)',
                'Thorbjørn Svenssen (104)',
                'Henning Berg (100)',
                'Erik Thorstvedt (97)',
                'John Carew (91)',
                'Brede Hangeland (91)',
                'Øyvind Leonhardsen (86)',
                'Morten Gamst Pedersen (83)',
                'Kjetil Rekdal (83)',
                'Steffen Iversen (79)',
            ],
            kilde: 'https://no.wikipedia.org/wiki/Norges_herrelandslag_i_fotball',
            år: '2026',
        },
        {
            id: '6',
            navn: 'Norges herrelandslags ti siste trenerperioder',
            fasit: [
                'Ståle Solbakken (2020–)',
                'Leif Gunnar Smerud (2020)',
                'Lars Lagerbäck (2017–2020)',
                'Per-Mathias Høgmo (2013–2016)',
                'Egil «Drillo» Olsen (2009–2013)',
                'Åge Hareide (2004–2008)',
                'Nils Johan Semb (1998–2003)',
                'Egil «Drillo» Olsen (1990–1998)',
                'Ingvar Stadheim (1988–1990)',
                'Tord Grip (1987–1988)',
            ],
            kilde: 'https://no.wikipedia.org/wiki/Liste_over_norske_landslagstrenere_i_fotball',
            år: '2025',
        },
        {
            id: '7',
            navn: 'Hvem scoret sist for Norge (herrer) i VM-kvalifiseringen 2025? (rangert fra siste mål)',
            fasit: [
                'Jørgen Strand Larsen',
                'Erling Haaland',
                'Antonio Nusa',
                'Alexander Sørloth',
                'Thelo Aasgaard',
                'Martin Ødegaard',
                'Felix Horn Myhre',
                'Kristoffer Ajer',
                'David Møller Wolfe',
                'Aron Dønnum',
            ],
            kilde: 'https://www.fotball.no/landslag/norge-a-herrer/?underside=statistikk',
            år: '2025',
        },
        {
            id: '8',
            navn: 'De ti siste vertsnasjonene i VM (herrer, 1990–2026)',
            fasit: [
                'Canada / Mexico / USA (2026)',
                'Qatar (2022)',
                'Russland (2018)',
                'Brasil (2014)',
                'Sør-Afrika (2010)',
                'Tyskland (2006)',
                'Japan / Sør-Korea (2002)',
                'Frankrike (1998)',
                'USA (1994)',
                'Italia (1990)',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_FIFA_World_Cup_hosts',
            år: '2026',
        },
        {
            id: '9',
            navn: 'Topp ti på FIFA-rankingen (herrer) per 11. juni 2026',
            fasit: [
                'Argentina (1877.27)',
                'Frankrike (1870.70)',
                'Spania (1856.03)',
                'England (1828.02)',
                'Portugal (1767.85)',
                'Brasil (1765.34)',
                'Marokko (1755.62)',
                'Nederland (1749.20)',
                'Tyskland (1743.54)',
                'Belgia (1733.93)',
            ],
            kilde: 'https://inside.fifa.com/fifa-world-ranking/men',
            år: '2026',
        },
    ],
    summer: [
        {
            id: '1',
            navn: 'Mest besøkte land i verden',
            fasit: [
                'Frankrike',
                'Spania',
                'USA',
                'Italia',
                'Tyrkia',
                'Mexico',
                'Storbritannia',
                'Tyskland',
                'Hellas',
                'Østerrike',
            ],
            kilde: 'https://en.wikipedia.org/wiki/World_Tourism_rankings',
            år: '2023',
        },
        {
            id: '2',
            navn: 'Studier med høyest snitt i Norge (førstegang)',
            fasit: [
                'Industriell økonomi og teknologiledelse, NTNU: 63',
                'Medisin, NTNU Trondheim: 62,2',
                'Medisin, NTNU Trondheim / Ålesund: 61,5',
                'Honoursprogam realfag, UiO: 61,5',
                'Medisin høst, UiO: 61,2',
                'Medisin, NTNU Trondheim / Levanger: 60,8',
                'Kybernetikk og robotikk, NTNU: 60,7',
                'Datateknologi, NTNU: 60,1',
                'Medisin vår, UiO: 60,1',
                'Medisin, UiB: 60,1',
            ],
            kilde: 'https://www.universitetsavisa.no/medisin-samordna-opptak-studentopptak/dette-studiet-har-na-702-i-poenggrense-ny-rekord/383387',
            år: '2023',
        },
        {
            id: '3',
            navn: 'Mest besøkte nettsider',
            fasit: [
                'google.com',
                'youtube.com',
                'facebook.com',
                'instagram.com',
                'x.com',
                'baidu.com',
                'wikipedia.org',
                'yahoo.com',
                'yandex.ru',
                'whatsapp.com',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_most-visited_websites',
            år: '2024',
        },
        {
            id: '4',
            navn: 'Rikeste i Norge',
            fasit: [
                'John Fredriksen',
                'Ole Andreas Halvorsen',
                'Odd Reitan',
                'Johan Johannson',
                'Johan H. Andresen',
                'Gustav Witzøe',
                'Kjell Inge Røkke',
                'Torstein Hagen',
                'Stein Erik Hagen',
                'Petter Anker Stordalen',
            ],
            kilde: 'https://www.finansavisen.no/kapital-index/norges-400-rikeste?zephr_sso_ott=FIjYuX',
            år: '2023',
        },
        {
            id: '5',
            navn: 'Lengste elver i verden',
            fasit: [
                'Nilen',
                'Amazonas',
                'Yangtze',
                'Mississippi',
                'Jenisej',
                'Huang He (Guleelven)',
                'Ob',
                'Paraná',
                'Kongo',
                'Amur',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_river_systems_by_length',
            år: '2024',
        },
        {
            id: '6',
            navn: 'Vanligste grunnstoff i universet',
            fasit: [
                'Hydrogen',
                'Helium',
                'Oksygen',
                'Karbon',
                'Neon',
                'Nitrogen',
                'Magnesium',
                'Silisium',
                'Jern',
                'Svovel',
            ],
            kilde: 'https://www.forbes.com/sites/startswithabang/2020/05/25/this-is-where-the-10-most-common-elements-in-the-universe-come-from/',
            år: '2022',
        },
        {
            id: '7',
            navn: 'Mest streamede artister på Spotify',
            fasit: [
                'Drake',
                'Taylor Swift',
                'Bad Bunny',
                'The Weeknd',
                'Justin Bieber',
                'Ed Sheeran',
                'Eminem',
                'Ariana Grande',
                'Kanye West',
                'Travis Scott',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_most-streamed_artists_on_Spotify',
            år: '2024',
        },
        {
            id: '8',
            navn: '10 siste vinnere av årets spellemann',
            fasit: [
                '2023 - Undergrunn',
                '2022 - Karpe',
                '2021 - Girl in Red',
                '2020 - TIX',
                '2019 - Sigrid',
                '2018 - Alan Walker',
                '2017 - Astrid S',
                '2016 - Marcus & Martinus',
                '2015 - Kygo',
                '2014 - Nico & Vinz',
            ],
            kilde: 'https://no.wikipedia.org/wiki/%C3%85rets_spellemann',
            år: '2023',
        },
        {
            id: '9',
            navn: 'Største universiteter og høgskoler i Norge etter antall studenter',
            fasit: [
                'Norges teknisk-naturvitenskapelige universitet (NTNU)',
                'Universitetet i Oslo (UiO)',
                'OsloMet – storbyuniversitetet',
                'Handelshøyskolen BI',
                'Universitetet i Bergen (UiB)',
                'UiT - Norges arktiske universitet',
                'Universitetet i Sørøst-Norge (USN)',
                'Høgskulen på Vestlandet',
                'Høyskolen Kristiania',
                'Høgskolen i Innlandet',
            ],
            kilde: 'https://www.ssb.no/utdanning/hoyere-utdanning/statistikk/studenter-i-universitets-og-hogskoleutdanning/artikler/dette-er-de-storste-studiestedene-i-norge',
            år: '2022',
        },
        {
            id: '10',
            navn: 'Filmer med høyest inntjening',
            fasit: [
                'Avatar',
                'Avengers: Endgame',
                'Avatar: The Way of Water',
                'Titanic',
                'Star Wars: The Force Awakens',
                'Avengers: Infinity War',
                'Spider-Man: No Way Home',
                'Jurassic World',
                'The Lion King',
                'The Avengers',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_highest-grossing_films',
            år: '2024',
        },
    ],
    christmas: [
        {
            id: '1',
            navn: 'Julefilmer som tjente mest penger på kino',
            fasit: [
                'Grinchen (2018)',
                'Hjemme Alene (1990)',
                'Hjemme Alene 2 (1992)',
                'How the Grinch Stole Christmas (2000)',
                'A Christmas Carol (2009)',
                'The Polar Express (2004)',
                'Love Actually (2003)',
                'Elf (2003)',
                'The Holiday (2006)',
                'The Santa Clause (1994)',
            ],
            kilde: 'https://www.cnbc.com/2022/12/17/these-are-the-10-biggest-christmas-movies-everand-where-to-watch-them.html',
            år: '2022',
        },
        {
            id: '2',
            navn: 'Mest spiste julemiddag i Norge',
            fasit: [
                'Ribbe',
                'Pinnekjøtt',
                'Kalkun',
                'Skinkestek',
                'Risgrøt',
                'Torsk',
                'Vegetarmat',
                'Annet',
                'Pizza',
                'Lutefisk',
            ],
            kilde: 'https://kommunikasjon.ntb.no/pressemelding/17947234/dette-skal-nordmenn-spise-til-jul-i-ar?publisherId=17847931',
            år: '2022',
        },
        {
            id: '3',
            navn: 'Mest spilte julesanger på Spotify Norge',
            fasit: [
                'Snowman - Sia',
                'All I Want for Christmas Is You - Mariah Carey',
                'Last Christmas - Wham!',
                'It\'s Beginning to Look a Lot like Christmas - Michael Bublé',
                'Himmel på jord - Kurt Nilsen',
                'Selmas Sang - Eva Weel Skram',
                'Home for Christmas - Maria Mena',
                'Driving Home for Christmas - Chris Rea',
                'Når snøen smelter - Astrid S',
                'Holly Jolly Christmas - Michael Bublé',
            ],
            kilde: 'https://kworb.net/spotify/country/no_daily.html',
            år: '2023',
        },
        {
            id: '4',
            navn: 'Største norske veldedige organisasjoner',
            fasit: [
                'Flyktninghjelpen',
                'Norges Røde Kors',
                'Redd Barna',
                'Kirkens Nødhjelp',
                'Norsk Folkehjelp',
                'SOS - barnebyer',
                'Plan Norge',
                'Leger Uten Grenser',
                'UNICEF Norge',
                'Strømmestiftelsen',
            ],
            kilde: 'https://gieffektivt.no/artikler/fundraisingrapport2021',
            år: '2021',
        },
        {
            id: '5',
            navn: 'Norges beste alpinanlegg',
            fasit: [
                'Hemsedal',
                'Trysil',
                'Hafjell',
                'Kvitfjell',
                'Hovden',
                'Stranda',
                'Geilo',
                'Oppdal',
                'Myrkdalen',
                'Gaustablikk',
            ],
            kilde: 'https://www.dn.no/staticprojects/2017/11/norges-25-raaeste-alpinanlegg/',
            år: '2017',
        },
        {
            id: '6',
            navn: 'Norges høyeste fjell',
            fasit: [
                'Galdhøpiggen',
                'Glittertind',
                'Store Skagastølstind',
                'Store Styggedalstind',
                'Skarstinden',
                'Veslpiggen',
                'Surtningssue',
                'Store Memurutinden',
                'Gjertvasstind',
                'Sentraltind',
            ],
            kilde: 'https://no.wikipedia.org/wiki/Liste_over_Norges_h%C3%B8yeste_fjell',
            år: '2023',
        },
        {
            id: '7',
            navn: 'Måneden flest blir født i Norge',
            fasit: [
                'April',
                'Mars',
                'Mai',
                'Juli',
                'Juni',
                'September',
                'August',
                'Januar',
                'Oktober',
                'Februar',
            ],
            kilde: 'https://www.babyverden.no/gravid/diverse/hvor-vanlig-er-fodselsdagen/',
            år: '2005',
        },
        {
            id: '8',
            navn: 'Flest google-søk i Norge: Film og TV',
            fasit: [
                'Oppenheimer',
                'The Last of Us',
                'Exit',
                'Barbie Movie',
                'Ginny and Georgia',
                'Everything Everywhere All at Once',
                'Stjernekamp',
                'Girls of Oslo',
                'Makata',
                'Hendelser ved vann',
            ],
            kilde: 'https://trends.google.com/trends/yis/2023/NO/',
            år: '2023',
        },
        {
            id: '9',
            navn: 'Flest google-søk i Norge: Personer',
            fasit: [
                'Reiulf Steen',
                'Emma Steinbakken',
                'Bjørn Eidsvåg',
                'Jon Fosse',
                'Ingebjørg Bratland',
                'Viggo Venn',
                'David Beckham',
                'Nora Haukland',
                'Andrew Tate',
                'Erna Solberg',
            ],
            kilde: 'https://trends.google.com/trends/yis/2023/NO/',
            år: '2023',
        },
        {
            id: '10',
            navn: 'Flest google-søk i verden: Utøvere',
            fasit: [
                'Damar Hamlin',
                'Kylian Mbappé',
                'Travis Kelce',
                'Ja Morant',
                'Harry Kane',
                'Novak Djokovic',
                'Carlos Alcaraz',
                'Rachin Ravindra',
                'Shubman Gill',
                'Kyrie Irving',
            ],
            kilde: 'https://trends.google.com/trends/yis/2023/GLOBAL/',
            år: '2023',
        },
        {
            id: '11',
            navn: 'Flest google-søk i verden: Sportslag',
            fasit: [
                'Inter Miami CF',
                'Los Angeles Lakers',
                'Al - Nassr FC',
                'Manchester City F.C',
                'Miami Heat',
                'Texas Rangers',
                'Al Hilal SFC',
                'Borussia Dortmund',
                'India national cricket team',
                'Boston Bruins',
            ],
            kilde: 'https://trends.google.com/trends/yis/2023/GLOBAL/',
            år: '2023',
        },
        {
            id: '12',
            navn: 'Kaldeste land i gjennomsnitt',
            fasit: [
                'Grønland (Danmark)',
                'Canada',
                'Russland',
                'Mongolia',
                'Norge',
                'Kirgisistan',
                'Island',
                'Finland',
                'Sverige',
                'Tadsjikistan',
            ],
            kilde: 'https://www.mappr.co/thematic-maps/coldest-countries/',
            år: '2023',
        },
        {
            id: '13',
            navn: 'Topp 10 filmer gitt ut i 2023 (IMDb)',
            fasit: [
                'Oppenheimer',
                'Past Lives',
                'Poor Things',
                'Killers of the Flower Moon',
                'Anatomy of a Fall',
                'Spider - Man: Across the Spider - Verse',
                'The Holdovers',
                'The Taste of Things',
                'Fallen Leaves',
                'About Dry Grasses',
            ],
            kilder: 'https://www.imdb.com/list/ls576754431/?sort=list_order,asc&st_dt=&mode=simple&page=1&ref_=ttls_vw_smp',
            år: '2023',
        },
        {
            id: '14',
            navn: 'Flest premier league poeng 2023',
            fasit: [
                'Manchester City (87)',
                'Aston Villa (82)',
                'Arsenal FC (81)',
                'Liverpool FC (81)',
                'Manchester United (74)',
                'Newcastle United (66)',
                'Tottenham Hotspur (66)',
                'Brighton & Hove Albion (65)',
                'West Ham United (56)',
                'Brentford FC (55)',
            ]
        },
        {
            id: '15',
            navn: 'Mest spilte spill på PC (november 2023)',
            fasit: [
                'Fortnite',
                'Minecraft',
                'Counter - Strike 2 & GO',
                'Call of Duty: Modern Warfare II / III / Warzone 2.0',
                'ROBLOX',
                'League of Legends',
                'The Sims 4',
                'Valorant',
                'Grand Theft Auto V',
                'Rocket League',
            ],
            kilde: 'https://newzoo.com/resources/rankings/top-20-pc-games',
            år: '2023',
        }
    ],
    default: [
        {
            id: '1',
            navn: 'Største land etter areal',
            fasit: [
                'Russland',
                'Canada',
                'USA',
                'Kina',
                'Brasil',
                'Australia',
                'India',
                'Argentina',
                'Kasakhstan',
                'Algerie',
            ],
            kilde: 'https://www.statista.com/statistics/262955/largest-countries-in-the-world/',
            år: '2023',
        },
        {
            id: '2',
            navn: 'Største land etter befolkning',
            fasit: [
                'Kina',
                'India',
                'USA',
                'Indonesia',
                'Pakistan',
                'Brasil',
                'Nigeria',
                'Bangladesh',
                'Russland',
                'Mexico',
            ],
            kilde: 'https://www.worldometers.info/world-population/population-by-country/',
            år: '2023',
        },
        {
            id: '3',
            navn: 'Største kommuner etter befolkning',
            fasit: [
                'Oslo',
                'Bergen',
                'Trondheim',
                'Stavanger',
                'Bærum',
                'Kristiansand',
                'Drammen',
                'Asker',
                'Lillestrøm',
                'Fredrikstad',
            ],
            kilde: 'https://www.ssb.no/befolkning/folketall/artikler/norges-100-mest-folkerike-kommuner/tabell-1.norges-100-mest-folkerike-kommuner',
            år: '2021',
        },
        {
            id: '4',
            navn: 'Mest fulgte personer på Instagram',
            fasit: [
                'Instagram',
                'Cristiano Ronaldo',
                'Lionel Messi',
                'Selena Gomez',
                'Kylie Jenner',
                'Dwayne Johnson',
                'Ariana Grande',
                'Kim Kardashian',
                'Beyoncé',
                'Khloé Kardashian',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_most-followed_Instagram_accounts',
            år: '2023',
        },
        {
            id: '5',
            navn: 'Mest streamede sanger på Spotify',
            fasit: [
                'Blinding Lights',
                'Shape of You',
                'Dance Monkey',
                'Someone You Loved',
                'Sunflower',
                'Rockstar',
                'One Dance',
                'Stay',
                'Closer',
                'Believer',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_most-streamed_songs_on_Spotify',
            år: '2023',
        },
        {
            id: '6',
            navn: 'Høyest ratede filmer på IMDb',
            fasit: [
                'The Shawshank Redemption',
                'The Godfather',
                'The Dark Knight',
                'The Godfather: Part II',
                '12 Angry Men',
                'Schindler\'s List',
                'The Lord of the Rings: The Return of the King',
                'Pulp Fiction',
                'The Lord of the Rings: The Fellowship of the Ring',
                'The Good, the Bad and the Ugly',
            ],
            kilde: 'https://www.imdb.com/chart/top/',
            år: '2023',
        },
        {
            id: '7',
            navn: 'Høyest ratede TV-serier på IMDb',
            fasit: [
                'Planet Earth II',
                'Breaking Bad',
                'Planet Earth',
                'Band of Brothers',
                'Chernobyl',
                'The Wire',
                'Avatar: The Last Airbender',
                'Blue Planet II',
                'The Sopranos',
                'Cosmos: A Spacetime Odyssey',
            ],
            kilde: 'https://www.imdb.com/chart/toptv/',
            år: '2023',
        },
        {
            id: '8',
            navn: 'Rikeste land etter BNP per innbygger',
            fasit: [
                'Luxembourg',
                'Irland',
                'Sveits',
                'Qatar',
                'Norge',
                'Singapore',
                'USA',
                'Island',
                'Australia',
                'Danmark',
            ],
            kilde: 'https://www.visualcapitalist.com/worlds-richest-countries-2023-gdp-per-capita/',
            år: '2023',
        },
        {
            id: '9',
            navn: 'Rikeste personer i verden',
            fasit: [
                'Bernard Arnault',
                'Elon Musk',
                'Jeff Bezos',
                'Larry Ellison',
                'Warren Buffett',
                'Bill Gates',
                'Michael Bloomberg',
                'Carlos Slim Helu',
                'Mukesh Ambani',
                'Steve Ballmer',
            ],
            kilde: 'https://www.forbes.com/billionaires/',
            år: '2023',
        },
        {
            id: '10',
            navn: 'Største fast food-kjeder etter antall lokasjoner',
            fasit: [
                'McDonald\'s',
                'Subway',
                'Starbucks',
                'KFC',
                'Burger King',
                'Pizza Hut',
                'Domino\'s Pizza',
                'Dunkin\' Donuts',
                'Krispy Kreme',
                'Hunt Brothers Pizza',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_the_largest_fast_food_restaurant_chains',
            år: '2022',
        },
        {
            id: '11',
            navn: 'Land etter antall medaljer i vinter-OL',
            fasit: [
                'Norge',
                'USA',
                'Tyskland',
                'Østerrike',
                'Canada',
                'Sovjetunionen',
                'Finland',
                'Sverige',
                'Sveits',
                'Nederland',
            ],
            kilde: 'https://www.vg.no/spesial/2018/ol/tom/medaljer/index.php',
            år: '2018',
        },
        {
            id: '12',
            navn: 'Land etter antall medaljer i sommer-OL',
            fasit: [
                'USA',
                'Sovjetunionen',
                'Storbritannia',
                'Frankrike',
                'Tyskland',
                'Kina',
                'Italia',
                'Australia',
                'Ungarn',
                'Sverige',
            ],
            kilde: 'https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table',
            år: '2023',
        },
        {
            id: '13',
            navn: 'Verdens mest verdifulle selskaper',
            fasit: [
                'Apple',
                'Microsoft',
                'Saudi Aramco',
                'Alphabet',
                'Amazon',
                'Nvidia',
                'Tesla',
                'Berkshire Hathaway',
                'Meta Platforms',
                'TSMC',
            ],
            kilde: 'https://companiesmarketcap.com/',
            år: '2023',
        },
        {
            id: '14',
            navn: 'Største byer i Australia etter befolkning',
            fasit: [
                'Sydney',
                'Melbourne',
                'Brisbane',
                'Perth',
                'Adelaide',
                'Gold Coast',
                'Newcastle',
                'Canberra',
                'Sunshine Coast',
                'Central Coast',
            ],
            kilde: 'https://metropole.com.au/australias-50-largest-cities/',
            år: '2023',
        },
        {
            id: '15',
            navn: 'Største sporter i verden etter antall utøvere',
            fasit: [
                'Fotball',
                'Cricket',
                'Hockey',
                'Tennis',
                'Volleyball',
                'Bordtennis',
                'Basketball',
                'Baseball',
                'Rugby',
                'Golf',
            ],
            kilde: 'https://www.worldatlas.com/articles/what-are-the-most-popular-sports-in-the-world.html',
            år: '2022',
        },
        {
            id: '16',
            navn: 'Største religioner i verden etter antall tilhengere',
            fasit: [
                'Kristendom',
                'Islam',
                'Ubestemt',
                'Hinduisme',
                'Buddhisme',
                'Kinesisk folketro',
                'Etnisk religion',
                'Afrikansk tradisjonell religion',
                'Sikhisme',
                'Spiritisme',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_religious_populations',
            år: '2023',
        },
        {
            id: '17',
            navn: 'Største byer i verden etter befolkning',
            fasit: [
                'Tokyo',
                'Delhi',
                'Shanghai',
                'Sao Paulo',
                'Mexico City',
                'Cairo',
                'Mumbai',
                'Beijing',
                'Dhaka',
                'Osaka',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_largest_cities',
            år: '2023',
        },
        {
            id: '18',
            navn: 'Minste land i verden etter areal',
            fasit: [
                'Vatikanstaten',
                'Monaco',
                'Nauru',
                'Tuvalu',
                'San Marino',
                'Liechtenstein',
                'Marshalløyene',
                'Saint Kitts og Nevis',
                'Maldivene',
                'Malta',
            ],
            kilde: 'https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_area',
            år: '2023',
        },
        {
            id: '19',
            navn: 'Største selskaper i Norge etter omsetning',
            fasit: [
                'Equinor',
                'Norsk Hydro',
                'Yara International',
                'Telenor',
                'KLP',
                'Norgesgruppen',
                'Storebrand',
                'DNB',
                'Reitangruppen',
                'Coop Norge',
            ],
            kilde: 'https://www.kapital.no/reportasjer/2020/07/16/7547889/regnearket-med-de-500-storste-selskapene-i-norge?zephr_sso_ott=vLS8D4',
            år: '2021',
        },
        {
            id: '20',
            navn: 'Mest snakkede språk i verden',
            fasit: [
                'Engelsk',
                'Mandarin',
                'Hindi',
                'Spansk',
                'Fransk',
                'Arabisk',
                'Bengali',
                'Russisk',
                'Portugisisk',
                'Urdu',
            ],
            kilde: 'https://www.berlitz.com/blog/most-spoken-languages-world',
            år: '2023',
        },
    ]
};

export default categories;