const categories = [
    {
        id: '1',
        navn: 'Største land etter areal',
        fasit: [
            'Russland',
            'Canada',
            'Kina',
            'USA',
            'Brasil',
            'Australia',
            'India',
            'Argentina',
            'Kasakhstan',
            'Algerie',
        ],
        kilde: 'https://www.worldometers.info/geography/largest-countries-in-the-world/',
    },
    {
        id: '2',
        navn: 'Største land etter befolkning',
        fasit: [
            'Kina',
            'India',
            'USA',
            'Indonesia',
            'Pakistan',
            'Brasil',
            'Nigeria',
            'Bangladesh',
            'Russland',
            'Mexico',
        ],
        kilde: 'https://www.worldometers.info/world-population/population-by-country/',
    },
    {
        id: '3',
        navn: 'Største kommuner etter befolkning',
        fasit: [
            'Oslo',
            'Bergen',
            'Trondheim',
            'Stavanger',
            'Bærum',
            'Kristiansand',
            'Drammen',
            'Asker',
            'Lillestrøm',
            'Fredrikstad',
        ],
        kilde: 'https://www.ssb.no/befolkning/folketall/artikler/norges-100-mest-folkerike-kommuner/tabell-1.norges-100-mest-folkerike-kommuner',
    },
    {
        id: '4',
        navn: 'Mest fulgte personer på Instagram',
        fasit: [
            'Instagram',
            'Cristiano Ronaldo',
            'Lionel Messi',
            'Selena Gomez',
            'Kylie Jenner',
            'Dwayne Johnson',
            'Ariana Grande',
            'Kim Kardashian',
            'Beyoncé',
            'Khloé Kardashian',
        ],
        kilde: 'https://en.wikipedia.org/wiki/List_of_most-followed_Instagram_accounts',
    },
    {
        id: '5',
        navn: 'Mest streamede sanger på Spotify',
        fasit: [
            'Blinding Lights',
            'Shape of You',
            'Dance Monkey',
            'Someone You Loved',
            'Sunflower',
            'Rockstar',
            'One Dance',
            'Stay',
            'Closer',
            'Believer',
        ],
        kilde: 'https://en.wikipedia.org/wiki/List_of_most-streamed_songs_on_Spotify',
    },
]

export default categories;